### PR TITLE
Add pointer to distro packages at https://apt.llvm.org

### PR DESCRIPTION
**Pull request by makslevental**
Probably useful...

### CODE REVIEW

**Comment by joker-eph** [comment]
I'm slightly hesitant about advertising these because they are mostly built for clang/LLVM and on the MLIR side we haven't been involved and don't really know what's supposed to work there. I wouldn't even know where to redirect someone who has questions there.

**Comment by makslevental** [comment]
It's pretty straightforward - there's a twice-daily pull and build (roughly starting [here](https://salsa.debian.org/pkg-llvm-team/llvm-toolchain/-/blob/snapshot/debian/orig-tar.sh#L101)). There's also a point of contact:

```shell
export DEBFULLNAME="Sylvestre Ledru"
export DEBEMAIL="sylvestre@debian.org"
```

If you don't think it should be advertised as first-party service that makes sense but I think it would be very useful for people to be aware of _somehow_? I mean it basically solves the problem of building from source for anyone that isn't doing in-tree dev _even if they want tip features_.

**Comment by joker-eph** [comment]
@sylvestre FYI

**Comment by sylvestre** [comment]
I think that, for most of the users, prebuilt packages are the way - and if it isn't apt.llvm.org, it will be packages from the distro :)

Also, if you don't like how mlir is packaged, I can always change it :)

**Comment by makslevental** [comment]
> Also, if you don't like how mlir is packaged, I can always change it :)

On this note I have a question (from a place of distro repo ignorance): is it possible in some way to publish those snapshot/dev packages with a commit hash such that a dependency on them can be pinned? Even if it's not exposed in the public `apt` API (i.e., one needs to download them manually and install them manually using `dpkg`). 

Reason being, having discovered that MLIR is published this way, I'd like to transition my CI to using the snapshot packages, but truly depending on tip will mean I'm killing myself to port my downstream MLIR code with every commit. Although maybe that kind of discipline is good :)

I think (obviously) caching twice-daily builds into perpetuity is an enormous storage burden but shorter spans would be useful too - probably at least a week to be useful but a month would make things comfortable.

**Comment by makslevental** [comment]
@sylvestre 

Okay I see that the `.deb`s are actually tagged with commit [short hash](https://apt.llvm.org/kinetic/pool/main/l/llvm-toolchain-snapshot/) so I will shortly be setting up a mirror here on github that caches those debs. Kudos to you!

**Pull request closed without merging**
