### PR TITLE
Switch code color scheme to light background

### PR DESCRIPTION
**Pull request by ftynse**
Alternating code blocks with black background and the text with white background creates large contrast boundaries that make it difficult to read text situated just next to them. They also break flow in "dark mode" or when colors are inverted on the client. Use the Pygments theme with white background instead. This is consistent with all major code sharing platforms, such as Github, and our own code review tooling.

Produced by running `hugo gen chromastyles --style pygments` for .scss, and sassc from there.

### CODE REVIEW

**Comment by ftynse** [comment]
Before and after views with color inversion.

Screenshot from 2022-12-05 16-41-58
Screenshot from 2022-12-05 16-41-21

**Comment by jpienaar** [comment]
This is copy from pygments to here? (basically, anything I should pay attention to code side vs the higher level question here)

**Comment by ftynse** [comment]
This is just produced by `hugo gen chromastyles --style pygments` and forwarded to the SASS compiler and minifier. (I'll update the commit message to reflect this).

**Review by jpienaar — APPROVED** [review]

**Comment by joker-eph** [comment]
Seems like a non-trivial change. I'll double check this tomorrow (or before
if I can)

**Comment by joker-eph** [comment]
Well it may seem trivial, but there are interactions that I'd like to check (sorry haven't time yet), like all the PNG we have in tutorials and other docs for example

**Comment by joker-eph** [comment]
Sorry for the delay, my local Hugo is too recent and we're using APIs that have been removed, I've been struggling to update our website and/or downgrade Hugo on my machine!

**Comment by ftynse** [comment]
Try with this patch:

```
diff --git a/website/themes/mlir/layouts/partials/head.html b/website/themes/mlir/layouts/partials/head.html
index 6c70f7501..5f7a5e5c0 100644
--- a/website/themes/mlir/layouts/partials/head.html
+++ b/website/themes/mlir/layouts/partials/head.html
@@ -11,7 +11,7 @@
 {{- else if isset .Site.Params "description" }}
 <meta name="description" content="{{ .Site.Params.description }}">
 {{- end }}
-{{ .Hugo.Generator }}
+{{ hugo.Generator }}
 <link href="{{ .Site.BaseURL }}index.xml" rel="alternate" type="application/rss+xml">
 <link rel="canonical" href="{{ .Permalink }}">
 <link rel="stylesheet" href="{{"css/theme.css" | absURL}}">
diff --git a/website/themes/mlir/layouts/partials/menu/slide-menu.html b/website/themes/mlir/layouts/partials/menu/slide-menu.html
index bc8e1eafe..5dd90cbd0 100644
--- a/website/themes/mlir/layouts/partials/menu/slide-menu.html
+++ b/website/themes/mlir/layouts/partials/menu/slide-menu.html
@@ -22,7 +22,7 @@
 {{- else -}}
   {{- safeHTML .Params.head -}}
   {{- $numberOfPages := (add (len .Pages) (len .Sections)) -}}
-<li class="{{ if .IsAncestor $currentNode }}parent{{ end }}{{ if eq .UniqueID $currentNode.UniqueID }} active{{ end }}{{ if ne $numberOfPages 0 }} has-sub-menu{{ end }}"><a href="{{ .URL }}">{{ safeHTML .Params.Pre }}{{ .Title }}{{ safeHTML .Params.Post }}{{ if ne $numberOfPages 0 }}{{ if .IsAncestor $currentNode }}<span class="mark opened">-</span>{{ else }}<span class="mark closed">+</span>{{ end }}{{ end }}</a>
+<li class="{{ if .IsAncestor $currentNode }}parent{{ end }}{{ if eq .File.UniqueID $currentNode.File.UniqueID }} active{{ end }}{{ if ne $numberOfPages 0 }} has-sub-menu{{ end }}"><a href="{{ .Permalink }}">{{ safeHTML .Params.Pre }}{{ .Title }}{{ safeHTML .Params.Post }}{{ if ne $numberOfPages 0 }}{{ if .IsAncestor $currentNode }}<span class="mark opened">-</span>{{ else }}<span class="mark closed">+</span>{{ end }}{{ end }}</a>
   {{ if ne $numberOfPages 0 }}
 <ul class="sub-menu">
     {{- .Scratch.Set "pages" .Pages -}}
@@ -51,7 +51,7 @@
 {{- end -}}
 {{- else -}}
   {{- if not .Params.Hidden -}}
-<li class="{{ if eq .UniqueID $currentNode.UniqueID }}active{{ end }}"><a href="{{ .URL }}">{{ safeHTML .Params.Pre }}{{ .Title }}{{ safeHTML .Params.Post }}</a></li>
+<li class="{{ if eq .File.UniqueID $currentNode.File.UniqueID }}active{{ end }}"><a href="{{ .Permalink }}">{{ safeHTML .Params.Pre }}{{ .Title }}{{ safeHTML .Params.Post }}</a></li>
   {{- end -}}
 {{ end -}}
 {{ end -}}
diff --git a/website/themes/mlir/layouts/partials/pagination.html b/website/themes/mlir/layouts/partials/pagination.html
index 7837118a8..c0f933e21 100644
--- a/website/themes/mlir/layouts/partials/pagination.html
+++ b/website/themes/mlir/layouts/partials/pagination.html
@@ -2,10 +2,10 @@
 <nav class="pagination">
 {{- template "pagination" dict "menu" .Site.Home "currentnode" $currentNode "menu_exclusion" .Site.Params.menu_exclusion -}}
 {{- with ($.Scratch.Get "prevPage") -}}
-<a class="nav nav-prev" href="{{ .URL }}" title="{{ .Title }}"><i class="fas fa-arrow-left" aria-hidden="true"></i> Prev - {{ .Title }}</a>
+<a class="nav nav-prev" href="{{ .Permalink }}" title="{{ .Title }}"><i class="fas fa-arrow-left" aria-hidden="true"></i> Prev - {{ .Title }}</a>
 {{ end -}}
 {{- with ($.Scratch.Get "nextPage") -}}
-<a class="nav nav-next" href="{{ .URL }}" title="{{ .Title }}">Next - {{ .Title }} <i class="fas fa-arrow-right" aria-hidden="true"></i></a>
+<a class="nav nav-next" href="{{ .Permalink }}" title="{{ .Title }}">Next - {{ .Title }} <i class="fas fa-arrow-right" aria-hidden="true"></i></a>
 {{- end }}
 </nav>
 
@@ -13,7 +13,7 @@
 {{- $currentNode := .currentnode -}}
 {{- $menu_exclusion := .menu_exclusion -}}
 
-{{- if hasPrefix $currentNode.URL .menu.URL -}}
+{{- if hasPrefix $currentNode.Permalink .menu.Permalink -}}
   {{- $currentNode.Scratch.Set "NextPageOK" "OK" -}}
   {{- if .menu.IsHome -}}
     {{- $currentNode.Scratch.Set "prevPage" "" -}}
```

**Comment by ftynse** [comment]
Ping

**Comment by joker-eph** [comment]
Thanks for the patch! I can run Hugo but I can't see the result, even though my browser seems to be set in dark mode, anything I am missing?

**Comment by ftynse** [comment]
As the commit description says, it only switches the color scheme for the code blocks. You *should* see it as code being rendered on a light background rather than black background. It does *not* add a dark theme. If you use an accessibility tool for system- or browser-wide color inversion (there's a plugin called dark reader, for example), you can see the effect with inverted colors as well.

**Comment by ftynse** [comment]
This is probably why you originally considered this change not being trivial... It has nothing to do with dark mode.

**Comment by joker-eph** [comment]
Indeed, your screenshots confused me about what's expected, so much less impactful that I thought originally :)
So here is the diff:

Screenshot 2023-01-05 at 11 29 35 AM
Screenshot 2023-01-05 at 11 29 29 AM


The background for the code is off-white but quite close: anything we could do to outline the code blocks a bit better from the background? (slight border or something like that?)

**Comment by ftynse** [comment]
Added a border

Screenshot from 2023-01-06 12-56-22

**Comment by joker-eph** [comment]
Sweet! Thanks

**Pull request merged**
