### PR TITLE
add name of unit testing target to docs

### PR DESCRIPTION
**Pull request by j2kun**

### CODE REVIEW

**Comment by joker-eph** [comment]
The current page has a separate section for [Command Line Incantations](https://mlir.llvm.org/getting_started/TestingGuide/#command-line-incantations) ; right now the current description does not tie things together and seems a bit misleading to me.

Also we should describe how to build and run a single unit-test.
I don't really think that the target documented here is ever useful actually.

**Comment by j2kun** [comment]
FWIW, the reason I made this change is because I was adding a unit test and couldn't find the target name to run just the unit tests (check-mlir takes too long, and this page suggests that it does not include the unit tests, as per the paragraph starting `Invoking the check-mlir target is roughly equivalent to...`).

I agree this page could use an overhaul. I can take a stab at it.

**Comment by joker-eph** [comment]
I'll submit a first draft soonish.

**Comment by joker-eph** [comment]
https://github.com/llvm/mlir-www/pull/189

**Pull request merged**
