### PR TITLE
Suggest to use free cast functions

### PR DESCRIPTION
**Pull request by kuhar**
This follows the consensus we reached in
https://discourse.llvm.org/t/preferred-casting-style-going-forward/68443a.

### CODE REVIEW

**Comment by joker-eph** [comment]
I am not sure the dev guide is the place for every depreciation.

maybe we could have a page dedicated to this and link to it from the dev guide ?

**Comment by kuhar** [comment]
> I am not sure the dev guide is the place for every depreciation.

This is not deprecated *yet* through function attributes, so I'd consider it a stylistic issue. WDYT?

**Comment by joker-eph** [comment]
I will start a new page for this kind of things, it is still valuable to maintain, thanks for the inspiration!

**Comment by joker-eph** [comment]
Here it is: https://github.com/llvm/mlir-www/pull/138

**Pull request closed without merging**
